rag_task:
  description: >
    For the given {query}, {id}, and {prev_id}:
    1. If {id} does not match {prev_id}, clean the database using the clear_database_tool. If {id} 
       and {prev_id} match, do not clean the database
    2. Additionally if {id} does not match {prev_id}, load the appropriate files into the database 
       using the load_file_tool with {id} as its parameter. If no files are found, return "No data 
       for this patient found". If {id} and {prev_id} match, do not load any files.
    3. Search the database using the rag_tool and to retrieve relevant information to the {query} 
       ensuring the information is about the patient with {id}.
    4. Evaluate if the retrieved information is meaningfully connected to {query}.
       - If yes, return the retrieved content.
       - If no, return "No relevant information found".
  expected_output: >
    - Relevant content about {query} if found.
    - "No data for this patient found" if no files were found corresponding to the {id}
    - "No relevant information found" only if retrieved content is completely unrelated.
  agent: rag_agent


llm_task:
  description: >
    Use the content generated by the rag_agent during the rag_task and answer the {query} to best 
    of your ability.
  expected_output: >
    The answer about {query}. Do not return JSON under any circumstances. Return a text answer to
    the {query}.
  agent: llm_agent
